//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Remote : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.remote_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchPadTouch
        {
            get
            {
                return SteamVR_Actions.remote_TouchPadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean LocomotionSwitch
        {
            get
            {
                return SteamVR_Actions.remote_LocomotionSwitch;
            }
        }
        
        public virtual SteamVR_Action_Boolean UISwitch
        {
            get
            {
                return SteamVR_Actions.remote_UISwitch;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapLeft
        {
            get
            {
                return SteamVR_Actions.remote_SnapLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapRight
        {
            get
            {
                return SteamVR_Actions.remote_SnapRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean Click
        {
            get
            {
                return SteamVR_Actions.remote_Click;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.remote_Haptic;
            }
        }
    }
}
