//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Knife : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.knife_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.knife_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.knife_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.knife_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.knife_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.knife_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.knife_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.knife_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.knife_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchPadTouch
        {
            get
            {
                return SteamVR_Actions.knife_TouchPadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean LocomotionSwitch
        {
            get
            {
                return SteamVR_Actions.knife_LocomotionSwitch;
            }
        }
        
        public virtual SteamVR_Action_Boolean UISwitch
        {
            get
            {
                return SteamVR_Actions.knife_UISwitch;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapLeft
        {
            get
            {
                return SteamVR_Actions.knife_SnapLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapRight
        {
            get
            {
                return SteamVR_Actions.knife_SnapRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean Cut
        {
            get
            {
                return SteamVR_Actions.knife_Cut;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.knife_Haptic;
            }
        }
    }
}
